![SGSSS Logo](../../img/SGSSS_Stacked.png)

# Practical Computational Methods for Social Scientists

## Introduction

Computational methods are transforming research practice across the disciplines. For social scientists these methods offer a number of valuable opportunities, including creating new datasets from digital sources; unearthing new insights and avenues for research from existing data sources; and improving the accuracy and efficiency of fundamental research activities.

In this lesson we introduce and apply the foundational preprocessing steps of text analysis for social science research.

### Aims

This lesson has two aims:
1. Demonstrate how to use R to preprocess text data relating to charitable activities.
2. Cultivate your computational thinking skills through coding examples. In particular, how to define and solve a data preprocessing problem using a computational method.

### Lesson details

* **Level**: Introductory
* **Time**: 40-60 minutes
* **Pre-requisites**: None
* **Audience**: Researchers and analysts from any disciplinary background
* **Learning outcomes**:
    1. Understand the key steps and concepts for getting social science data ready for text analysis.
    2. Be able to use R for preprocessing text data.

## Guide to using this resource

This learning resource was built using <a href="https://jupyter.org/" target=_blank>Jupyter Notebook</a>, an open-source software application that allows you to mix code, results and narrative in a single document. As <a href="https://jupyter4edu.github.io/jupyter-edu-book/" target=_blank>Barba et al. (2019)</a> espouse:
> In a world where every subject matter can have a data-supported treatment, where computational devices are omnipresent and pervasive, the union of natural language and computation creates compelling communication and learning opportunities.

If you are familiar with Jupyter notebooks then skip ahead to the main content (*How do we prepare social science data for text analysis?*). Otherwise, the following is a quick guide to navigating and interacting with the notebook.

### Interaction

**You only need to execute the code that is contained in sections which are marked by `In []`.**

To execute a cell, click or double-click the cell and press the `Run` button on the top toolbar (you can also use the keyboard shortcut Shift + Enter).

Try it for yourself:

In [ ]:
print("Enter your name and press enter:")
name = input()
print("\r")
print("Hello {}, enjoy learning more about Python and web-scraping!".format(name))

### Learn more

Jupyter notebooks provide rich, flexible features for conducting and documenting your data analysis workflow. To learn more about additional notebook features, we recommend working through some of the <a href="https://github.com/darribas/gds19/blob/master/content/labs/lab_00.ipynb" target=_blank>materials</a> provided by Dani Arribas-Bel at the University of Liverpool.

## How do we prepare social science data for text analysis?

There are a number of common, initial steps before you can perform text analysis with social science data. Grimmer et al., (2022) suggest the following workflow (Grimmer et al., 2022):
1. Choose unit of analysis
2. Tokenise
3. Reduce complexity:
   * Convert to lowercase
   * Remove punctuation
   * Remove stop words
   * Create equivalence classes (lemmatisation / stemming)
   * Filter by frequency
4. Construct document-feature matrix (W = N*J) (Wij = count of type j in document i)

## Preliminaries

First we need to ensure Python has the functionality it needs for text analysis. As you will see, it needs quite a bit of extra functionality, so this may take some time to install / import depending on your machine.

In [7]:
install.packages("vctrs")

Installing package into 'C:/Users/diarm/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

package 'vctrs' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'vctrs'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\diarm\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\diarm\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied"
Warning message:
"restored 'vctrs'"

The downloaded binary packages are in
	C:\Users\diarm\AppData\Local\Temp\RtmpgpjZvc\downloaded_packages

In [1]:
# Install additional packages - only run once per machine
install.packages("quanteda")
install.packages("quanteda.textstats")
install.packages("dplyr")
install.packages("tm")
install.packages("stringr")

Installing package into 'C:/Users/diarm/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

also installing the dependencies 'ISOcodes', 'fastmatch', 'SnowballC', 'stopwords'

package 'ISOcodes' successfully unpacked and MD5 sums checked
package 'fastmatch' successfully unpacked and MD5 sums checked
package 'SnowballC' successfully unpacked and MD5 sums checked
package 'stopwords' successfully unpacked and MD5 sums checked
package 'quanteda' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\diarm\AppData\Local\Temp\RtmpgpjZvc\downloaded_packages

Installing package into 'C:/Users/diarm/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

also installing the dependency 'vctrs'

package 'vctrs' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'vctrs'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\diarm\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\diarm\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied"
Warning message:
"restored 'vctrs'"

package 'dplyr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\diarm\AppData\Local\Temp\RtmpgpjZvc\downloaded_packages

Installing package into 'C:/Users/diarm/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

also installing the dependencies 'NLP', 'slam'

package 'NLP' successfully unpacked and MD5 sums checked
package 'slam' successfully unpacked and MD5 sums checked
package 'tm' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\diarm\AppData\Local\Temp\RtmpgpjZvc\downloaded_packages

Installing package into 'C:/Users/diarm/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)

package 'stringr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\diarm\AppData\Local\Temp\RtmpgpjZvc\downloaded_packages

In [6]:
# Load necessary libraries
library(quanteda)      # For text processing
library(quanteda.textstats)  # For text statistics
library(dplyr)         # For data manipulation
library(readr)         # For reading CSV files
library(tm)            # For additional text preprocessing
library(stringr)       # For string manipulation

Warning message:
"package 'dplyr' was built under R version 4.3.3"

ERROR: Error: package or namespace load failed for 'dplyr' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'vctrs' 0.6.3 is already loaded, but >= 0.6.4 is required

How do we know what modules we need for text analysis? Thankfully it is an established method, therefore others have figured this out for us:
* https://github.com/UKDataServiceOpen/text-mining/blob/407d16015ba270b4e39462c20de9b370c4e78563/code/1-Processing.ipynb
* https://github.com/UKDataServiceOpen/text-mining/blob/407d16015ba270b4e39462c20de9b370c4e78563/code/2-Extraction.ipynb

Modules are additional techniques or functions that are not present when you launch Python. Some do not even come with Python when you download it and must be installed on your machine separately - think of using `ssc install <package>` in Stata, or `install.packages(<package>)` in R. For now just understand that many useful modules need to be imported every time you start a new Python session.

### Import data

A second important preliminary step is to import the text data you will be using.

In [3]:
dfolder = "../../data/" # define folder where data is stored
infile = dfolder + "acnc-overseas-activities-2022.csv" # define file to be imported

data = pd.read_csv(infile, encoding="ISO-8859-1")

In [4]:
data.sample(10)

,abn,charityname,registrationstatus,charitysize,activity_desc,other_activity_desc
1884,82041296423,Christadelphian Indian Rehabilitation Inc.,Registered,Small,We provide funds for the daily needs and rehab...,NaN
1170,55129338825,Disaster Aid Australia,Registered,Small,DAA provides disaster relief via our Smart Aid...,NaN
149,16641057338,CANVA FOUNDATION LIMITED,Registered,Large,Our mission - to do the most good we can do - ...,NaN
135,16142002908,Save A Child's Heart Australia,Registered,Medium,We transfer funds the charity's headoffice in ...,NaN
1040,49637552697,LIGER LEADERSHIP ACADEMY AUSTRALIA LTD,Registered,Small,Liger Leadership Academy Cambodia educates pro...,NaN
2159,91933490636,JONGLEI FOOD SECURITY INITIATIVE (JFS)INC,Registered,Small,Summary of activities: We provide agriculture...,NaN
1652,73088112261,Children First Foundation,Registered,Medium,We are committed to ensuring timely access to ...,NaN
1392,63612863064,Hadassah Charity Limited,Registered,Large,Hadassah Charity Ltd (Hadassah Australia) is a...,NaN
680,36558788040,Rea Thusa Incorporated,Registered,Small,Through a volunteer country director in Lesoth...,NaN
790,40612577036,CAUSINDY Ltd,Registered,Small,We executed programs that aimed to improve Aus...,NaN

In [5]:
data["activity_desc"].sample(10)

980     Monies are used by established groups among th...
1735    Tutoring support for at-risk students Skills d...
1951    Maternity care for peoples in Uganda Well buil...
1635    Financial support for overseas mission activit...
107     GHARA provides individualised supports in the ...
537                           support of overseas pastors
2080    Providing a Scholarship by the Brian May Trust...
1995    With Brownsville Partnership, we are running a...
529     1- Save a Life Program (Cure for Hep C and eli...
1039    We know that solutions to some of the world's ...
Name: activity_desc, dtype: object

###  Choose unit of analysis

A fundamental task in social science research more generally, it is important for text analysis also. In many cases the unit of analysis is the **document**; that is, we are interested in measuring relevant, salient features of a document (e.g., author, style, sentiment, topics) and comparing these across other documents. However we can also select other, often small units of analysis such as paragraphs or sentences - then we can compare *within* and *between* documents e.g., how do political speeches develop rom beginning to end, and across different speeches?

In our analysis the unit of analysis is the **document**: each row in the raw data represents a single charity's description of its overseas activities. This description is what serves as the document.

### Pilot

Before unleashing this workflow on a corpus, let's apply it to a single document so we can get a sense of what happens at each step. Below we select the text in the `activity_desc` column for the 501st row in the dataset.

In [6]:
sample_text = data.iloc[500, data.columns.get_loc("activity_desc")]
sample_text

"As an Australian charity, we must comply to External Standards of Conduct (ECS), helping us manage our activities and resources outside of Australia, per Nest s Overseas Operations Policy. Nest believes that every child deserves a chance for a better life. Therefore, Nest s commitment can be expressed in many different forms, from encouragement to financial, material, or in-kind assistance. Regardless of the form, our support of a disadvantaged community or an individual always occurs within a ThirdParty relationship. Through many years of experience donating in the Balkans (since 2013), Nest Inc. have established networks with orphanages, youth centres and children's hospitals that are consistent with our charity s not-for-profit purpose. By working closely with the top management of these organisations, it allows us to assess their essential needs that will improve their living conditions, and finally, based on our donor capabilities, identify whom to donate to."

**TASK**: Read through the above activity description and note any issues with the text e.g., misspellings, odd words, improper punctuation.

#### Tokenise

The next major step is to split the text into subunits of analysis. The most common subunit of interest is a type (or word). This approach treats every typ

In [7]:
sample_words = word_tokenize(sample_text)
print(sample_words)  # comma-separated list of tokens in the text
print(len(sample_words)) # number of tokens in text
print(len(set(sample_words))) # number of types in text

['As', 'an', 'Australian', 'charity', ',', 'we', 'must', 'comply', 'to', 'External', 'Standards', 'of', 'Conduct', '(', 'ECS', ')', ',', 'helping', 'us', 'manage', 'our', 'activities', 'and', 'resources', 'outside', 'of', 'Australia', ',', 'per', 'Nest', 's', 'Overseas', 'Operations', 'Policy', '.', 'Nest', 'believes', 'that', 'every', 'child', 'deserves', 'a', 'chance', 'for', 'a', 'better', 'life', '.', 'Therefore', ',', 'Nest', 's', 'commitment', 'can', 'be', 'expressed', 'in', 'many', 'different', 'forms', ',', 'from', 'encouragement', 'to', 'financial', ',', 'material', ',', 'or', 'in-kind', 'assistance', '.', 'Regardless', 'of', 'the', 'form', ',', 'our', 'support', 'of', 'a', 'disadvantaged', 'community', 'or', 'an', 'individual', 'always', 'occurs', 'within', 'a', 'ThirdParty', 'relationship', '.', 'Through', 'many', 'years', 'of', 'experience', 'donating', 'in', 'the', 'Balkans', '(', 'since', '2013', ')', ',', 'Nest', 'Inc.', 'have', 'established', 'networks', 'with', 'orphanages', ',', 'youth', 'centres', 'and', 'children', "'s", 'hospitals', 'that', 'are', 'consistent', 'with', 'our', 'charity', 's', 'not-for-profit', 'purpose', '.', 'By', 'working', 'closely', 'with', 'the', 'top', 'management', 'of', 'these', 'organisations', ',', 'it', 'allows', 'us', 'to', 'assess', 'their', 'essential', 'needs', 'that', 'will', 'improve', 'their', 'living', 'conditions', ',', 'and', 'finally', ',', 'based', 'on', 'our', 'donor', 'capabilities', ',', 'identify', 'whom', 'to', 'donate', 'to', '.']
172
117

We can see that tokenising is an important but not infallible step in preprocessing text data. Tokenisers generally work by splitting text into separate components. How do these approaches know when one component (e.g., word) begins and another ends? They use whitespace as a delimiter / separator. This works very well but not perfectly, as you can see punctuation like commas, periods and brackets are identified as tokens in the text. We are generally not interested in punctuation for analysis, so we need a later step to remove these instances.

We can also tokenise the text into sentences if these were our linguistic subunits of interest.

In [8]:
sample_sent = sent_tokenize(sample_text)
print(sample_sent) # comma-separated list of sentences in the text
print(len(sample_sent)) # number of sentences in text

['As an Australian charity, we must comply to External Standards of Conduct (ECS), helping us manage our activities and resources outside of Australia, per Nest s Overseas Operations Policy.', 'Nest believes that every child deserves a chance for a better life.', 'Therefore, Nest s commitment can be expressed in many different forms, from encouragement to financial, material, or in-kind assistance.', 'Regardless of the form, our support of a disadvantaged community or an individual always occurs within a ThirdParty relationship.', "Through many years of experience donating in the Balkans (since 2013), Nest Inc. have established networks with orphanages, youth centres and children's hospitals that are consistent with our charity s not-for-profit purpose.", 'By working closely with the top management of these organisations, it allows us to assess their essential needs that will improve their living conditions, and finally, based on our donor capabilities, identify whom to donate to.']
6

#### Reduce complexity

##### Convert to lowercase

Unless capitalisation is of analytical interest, we generally convert all tokens to lowercase. In essence we want to avoid situations where we treat the same words as if they different e.g., are "The" and "the" different words? "Charity" and "CHARITY"?

In [9]:
sample_lower = [word.lower() for word in sample_words]
print(sample_lower)
print(len(sample_lower))

['as', 'an', 'australian', 'charity', ',', 'we', 'must', 'comply', 'to', 'external', 'standards', 'of', 'conduct', '(', 'ecs', ')', ',', 'helping', 'us', 'manage', 'our', 'activities', 'and', 'resources', 'outside', 'of', 'australia', ',', 'per', 'nest', 's', 'overseas', 'operations', 'policy', '.', 'nest', 'believes', 'that', 'every', 'child', 'deserves', 'a', 'chance', 'for', 'a', 'better', 'life', '.', 'therefore', ',', 'nest', 's', 'commitment', 'can', 'be', 'expressed', 'in', 'many', 'different', 'forms', ',', 'from', 'encouragement', 'to', 'financial', ',', 'material', ',', 'or', 'in-kind', 'assistance', '.', 'regardless', 'of', 'the', 'form', ',', 'our', 'support', 'of', 'a', 'disadvantaged', 'community', 'or', 'an', 'individual', 'always', 'occurs', 'within', 'a', 'thirdparty', 'relationship', '.', 'through', 'many', 'years', 'of', 'experience', 'donating', 'in', 'the', 'balkans', '(', 'since', '2013', ')', ',', 'nest', 'inc.', 'have', 'established', 'networks', 'with', 'orphanages', ',', 'youth', 'centres', 'and', 'children', "'s", 'hospitals', 'that', 'are', 'consistent', 'with', 'our', 'charity', 's', 'not-for-profit', 'purpose', '.', 'by', 'working', 'closely', 'with', 'the', 'top', 'management', 'of', 'these', 'organisations', ',', 'it', 'allows', 'us', 'to', 'assess', 'their', 'essential', 'needs', 'that', 'will', 'improve', 'their', 'living', 'conditions', ',', 'and', 'finally', ',', 'based', 'on', 'our', 'donor', 'capabilities', ',', 'identify', 'whom', 'to', 'donate', 'to', '.']
172

##### Spell check

This step is often not necessary and can be computationally intensive. However here is how you can do it.

check = Speller(lang='en')
sample_correct_spell = []

for word in sample_lower:
    sample_correct_spell.append(check(word))

sample_correct_spell

##### Remove punctuation

In [10]:
sample_no_punct = [w.translate(table_punctuation) for w in sample_lower]  
print(sample_no_punct)
print(len(sample_no_punct))

['as', 'an', 'australian', 'charity', '', 'we', 'must', 'comply', 'to', 'external', 'standards', 'of', 'conduct', '', 'ecs', '', '', 'helping', 'us', 'manage', 'our', 'activities', 'and', 'resources', 'outside', 'of', 'australia', '', 'per', 'nest', 's', 'overseas', 'operations', 'policy', '', 'nest', 'believes', 'that', 'every', 'child', 'deserves', 'a', 'chance', 'for', 'a', 'better', 'life', '', 'therefore', '', 'nest', 's', 'commitment', 'can', 'be', 'expressed', 'in', 'many', 'different', 'forms', '', 'from', 'encouragement', 'to', 'financial', '', 'material', '', 'or', 'inkind', 'assistance', '', 'regardless', 'of', 'the', 'form', '', 'our', 'support', 'of', 'a', 'disadvantaged', 'community', 'or', 'an', 'individual', 'always', 'occurs', 'within', 'a', 'thirdparty', 'relationship', '', 'through', 'many', 'years', 'of', 'experience', 'donating', 'in', 'the', 'balkans', '', 'since', '2013', '', '', 'nest', 'inc', 'have', 'established', 'networks', 'with', 'orphanages', '', 'youth', 'centres', 'and', 'children', 's', 'hospitals', 'that', 'are', 'consistent', 'with', 'our', 'charity', 's', 'notforprofit', 'purpose', '', 'by', 'working', 'closely', 'with', 'the', 'top', 'management', 'of', 'these', 'organisations', '', 'it', 'allows', 'us', 'to', 'assess', 'their', 'essential', 'needs', 'that', 'will', 'improve', 'their', 'living', 'conditions', '', 'and', 'finally', '', 'based', 'on', 'our', 'donor', 'capabilities', '', 'identify', 'whom', 'to', 'donate', 'to', '']
172

At this point there are still some issues:
* There are spaces operationalised as tokens e.g., where there used to be punctuation
* There are tokens consisting of a single character e.g., a number or letter that was separated from its apostrophe

In [11]:
sample_no_space = list(filter(None, sample_no_punct)) # strip out empty spaces
print(sample_no_space)
print(len(sample_no_space))

['as', 'an', 'australian', 'charity', 'we', 'must', 'comply', 'to', 'external', 'standards', 'of', 'conduct', 'ecs', 'helping', 'us', 'manage', 'our', 'activities', 'and', 'resources', 'outside', 'of', 'australia', 'per', 'nest', 's', 'overseas', 'operations', 'policy', 'nest', 'believes', 'that', 'every', 'child', 'deserves', 'a', 'chance', 'for', 'a', 'better', 'life', 'therefore', 'nest', 's', 'commitment', 'can', 'be', 'expressed', 'in', 'many', 'different', 'forms', 'from', 'encouragement', 'to', 'financial', 'material', 'or', 'inkind', 'assistance', 'regardless', 'of', 'the', 'form', 'our', 'support', 'of', 'a', 'disadvantaged', 'community', 'or', 'an', 'individual', 'always', 'occurs', 'within', 'a', 'thirdparty', 'relationship', 'through', 'many', 'years', 'of', 'experience', 'donating', 'in', 'the', 'balkans', 'since', '2013', 'nest', 'inc', 'have', 'established', 'networks', 'with', 'orphanages', 'youth', 'centres', 'and', 'children', 's', 'hospitals', 'that', 'are', 'consistent', 'with', 'our', 'charity', 's', 'notforprofit', 'purpose', 'by', 'working', 'closely', 'with', 'the', 'top', 'management', 'of', 'these', 'organisations', 'it', 'allows', 'us', 'to', 'assess', 'their', 'essential', 'needs', 'that', 'will', 'improve', 'their', 'living', 'conditions', 'and', 'finally', 'based', 'on', 'our', 'donor', 'capabilities', 'identify', 'whom', 'to', 'donate', 'to']
148

The text looks much cleaner and we have reduced the number of tokens as well (good for computational efficiency and substantive clarity).

##### Remove stopwords

In [12]:
sample_no_stop_words = []

for word in sample_no_space:
    if word not in stop_words:
        sample_no_stop_words.append(word)

In [13]:
print(sample_no_stop_words)
print(len(sample_no_stop_words))

['australian', 'charity', 'must', 'comply', 'external', 'standards', 'conduct', 'ecs', 'helping', 'us', 'manage', 'activities', 'resources', 'outside', 'australia', 'per', 'nest', 'overseas', 'operations', 'policy', 'nest', 'believes', 'every', 'child', 'deserves', 'chance', 'better', 'life', 'therefore', 'nest', 'commitment', 'expressed', 'many', 'different', 'forms', 'encouragement', 'financial', 'material', 'inkind', 'assistance', 'regardless', 'form', 'support', 'disadvantaged', 'community', 'individual', 'always', 'occurs', 'within', 'thirdparty', 'relationship', 'many', 'years', 'experience', 'donating', 'balkans', 'since', '2013', 'nest', 'inc', 'established', 'networks', 'orphanages', 'youth', 'centres', 'children', 'hospitals', 'consistent', 'charity', 'notforprofit', 'purpose', 'working', 'closely', 'top', 'management', 'organisations', 'allows', 'us', 'assess', 'essential', 'needs', 'improve', 'living', 'conditions', 'finally', 'based', 'donor', 'capabilities', 'identify', 'donate']
90

##### Create equivalence classes: Stemming

In [14]:
sample_stemmed = [porter.stem(word) for word in sample_no_stop_words]
print(sample_stemmed)
print(len(sample_stemmed)) # number of tokens
print(len(set(sample_stemmed))) # number of terms

['australian', 'chariti', 'must', 'compli', 'extern', 'standard', 'conduct', 'ec', 'help', 'us', 'manag', 'activ', 'resourc', 'outsid', 'australia', 'per', 'nest', 'oversea', 'oper', 'polici', 'nest', 'believ', 'everi', 'child', 'deserv', 'chanc', 'better', 'life', 'therefor', 'nest', 'commit', 'express', 'mani', 'differ', 'form', 'encourag', 'financi', 'materi', 'inkind', 'assist', 'regardless', 'form', 'support', 'disadvantag', 'commun', 'individu', 'alway', 'occur', 'within', 'thirdparti', 'relationship', 'mani', 'year', 'experi', 'donat', 'balkan', 'sinc', '2013', 'nest', 'inc', 'establish', 'network', 'orphanag', 'youth', 'centr', 'children', 'hospit', 'consist', 'chariti', 'notforprofit', 'purpos', 'work', 'close', 'top', 'manag', 'organis', 'allow', 'us', 'assess', 'essenti', 'need', 'improv', 'live', 'condit', 'final', 'base', 'donor', 'capabl', 'identifi', 'donat']
90
81

Notice what has happened words like "comply", "external" and "charity". They are now expressed in their common root form and thus are no longer words that we would find in the English dictionary. These are examples of terms rather than types.

**QUESTION:** What is the value of transforming words to their root form?

##### Create equivalence classes: Lemmatisation

This is an alternative to stemming that maps words to a common word based on semantic meaning e.g., "car" and "cars" map to "car".

In [15]:
lemmatizer.lemmatize("car")

'car'

In [16]:
lemmatizer.lemmatize("cars")

'car'

In [17]:
sample_lemmed = [lemmatizer.lemmatize(word) for word in sample_no_stop_words]
print(sample_lemmed)
print(len(sample_lemmed)) # number of tokens
print(len(set(sample_lemmed))) # number of terms

['australian', 'charity', 'must', 'comply', 'external', 'standard', 'conduct', 'ec', 'helping', 'u', 'manage', 'activity', 'resource', 'outside', 'australia', 'per', 'nest', 'overseas', 'operation', 'policy', 'nest', 'belief', 'every', 'child', 'deserves', 'chance', 'better', 'life', 'therefore', 'nest', 'commitment', 'expressed', 'many', 'different', 'form', 'encouragement', 'financial', 'material', 'inkind', 'assistance', 'regardless', 'form', 'support', 'disadvantaged', 'community', 'individual', 'always', 'occurs', 'within', 'thirdparty', 'relationship', 'many', 'year', 'experience', 'donating', 'balkan', 'since', '2013', 'nest', 'inc', 'established', 'network', 'orphanage', 'youth', 'centre', 'child', 'hospital', 'consistent', 'charity', 'notforprofit', 'purpose', 'working', 'closely', 'top', 'management', 'organisation', 'allows', 'u', 'ass', 'essential', 'need', 'improve', 'living', 'condition', 'finally', 'based', 'donor', 'capability', 'identify', 'donate']
90
82

**QUESTION:** What is the difference between stemming and lemmatisation in the example above, both in terms of the number of terms / tokens and the readability of the words?

##### Filter by frequency

As a final step we may want to remove very common or very rare words from the corpus: this aids both substantive interpretations (e.g., perhaps all charities mention their beneficiaries in their activity descriptions) or certain words only appear once across the entire corpus (e.g., misspellings or acroynms).

We can view the frequency table of the terms in our corpus as follows:

In [18]:
freq_table = Counter(sample_lemmed)
print(freq_table)

Counter({'nest': 4, 'charity': 2, 'u': 2, 'child': 2, 'many': 2, 'form': 2, 'australian': 1, 'must': 1, 'comply': 1, 'external': 1, 'standard': 1, 'conduct': 1, 'ec': 1, 'helping': 1, 'manage': 1, 'activity': 1, 'resource': 1, 'outside': 1, 'australia': 1, 'per': 1, 'overseas': 1, 'operation': 1, 'policy': 1, 'belief': 1, 'every': 1, 'deserves': 1, 'chance': 1, 'better': 1, 'life': 1, 'therefore': 1, 'commitment': 1, 'expressed': 1, 'different': 1, 'encouragement': 1, 'financial': 1, 'material': 1, 'inkind': 1, 'assistance': 1, 'regardless': 1, 'support': 1, 'disadvantaged': 1, 'community': 1, 'individual': 1, 'always': 1, 'occurs': 1, 'within': 1, 'thirdparty': 1, 'relationship': 1, 'year': 1, 'experience': 1, 'donating': 1, 'balkan': 1, 'since': 1, '2013': 1, 'inc': 1, 'established': 1, 'network': 1, 'orphanage': 1, 'youth': 1, 'centre': 1, 'hospital': 1, 'consistent': 1, 'notforprofit': 1, 'purpose': 1, 'working': 1, 'closely': 1, 'top': 1, 'management': 1, 'organisation': 1, 'allows': 1, 'ass': 1, 'essential': 1, 'need': 1, 'improve': 1, 'living': 1, 'condition': 1, 'finally': 1, 'based': 1, 'donor': 1, 'capability': 1, 'identify': 1, 'donate': 1})

As we are only working with one document at the moment we won't remove any words just yet. However there are better approaches for handling common / rare terms in a corpus that we shall see shortly (e.g., weighting). For completeness sake, here is how you could remove words based on their frequencies:

In [19]:
max_count = max(freq_table.values()) # find most frequency word(s)
min_count = min(freq_table.values()) # find most frequency word(s)

sample_filtered = [word for word in sample_lemmed if freq_table[word] not in (max_count, min_count)] # create new list of terms

print("Original tokens:", sample_lemmed)
print("Filtered tokens:", sample_filtered)

Original tokens: ['australian', 'charity', 'must', 'comply', 'external', 'standard', 'conduct', 'ec', 'helping', 'u', 'manage', 'activity', 'resource', 'outside', 'australia', 'per', 'nest', 'overseas', 'operation', 'policy', 'nest', 'belief', 'every', 'child', 'deserves', 'chance', 'better', 'life', 'therefore', 'nest', 'commitment', 'expressed', 'many', 'different', 'form', 'encouragement', 'financial', 'material', 'inkind', 'assistance', 'regardless', 'form', 'support', 'disadvantaged', 'community', 'individual', 'always', 'occurs', 'within', 'thirdparty', 'relationship', 'many', 'year', 'experience', 'donating', 'balkan', 'since', '2013', 'nest', 'inc', 'established', 'network', 'orphanage', 'youth', 'centre', 'child', 'hospital', 'consistent', 'charity', 'notforprofit', 'purpose', 'working', 'closely', 'top', 'management', 'organisation', 'allows', 'u', 'ass', 'essential', 'need', 'improve', 'living', 'condition', 'finally', 'based', 'donor', 'capability', 'identify', 'donate']
Filtered tokens: ['charity', 'u', 'child', 'many', 'form', 'form', 'many', 'child', 'charity', 'u']

#### Create Document-Term Matrix

If you are happy with the preprocessing steps above, both in terms of effect and order, we can convert the text to a numeric format suitable for analysis. This format is known as a Document-Term Matrix (DTM) or Document-Feature Matrix (DFM) - the latter is a more general format than the former. Both simply represent a document or corpus in a tabular format, where every row represents a document and every column represents a term or feature relating to the document. If you are a quantitative researcher then this format will be familiar to you e.g., the rows are units of analysis and the columns are variables representative numeric characteristics of the units of analysis.

In order to the create the DTM we need to convert the list of terms into a single string of terms as follows:

In [20]:
sample_text = " ".join(sample_lemmed)
sample_text

'australian charity must comply external standard conduct ec helping u manage activity resource outside australia per nest overseas operation policy nest belief every child deserves chance better life therefore nest commitment expressed many different form encouragement financial material inkind assistance regardless form support disadvantaged community individual always occurs within thirdparty relationship many year experience donating balkan since 2013 nest inc established network orphanage youth centre child hospital consistent charity notforprofit purpose working closely top management organisation allows u ass essential need improve living condition finally based donor capability identify donate'

We take the single string of terms and represent them in the "bag of words" format - there are a couple of ways of doing this.

In [21]:
bow = FreqDist(sample_lemmed)
#print(dict(bow))
dtm = pd.DataFrame([bow])
dtm

,australian,charity,must,comply,external,standard,conduct,ec,helping,u,...,need,improve,living,condition,finally,based,donor,capability,identify,donate
0,1,2,1,1,1,1,1,1,1,2,...,1,1,1,1,1,1,1,1,1,1

In [22]:
print(dtm.shape)

(1, 82)

Or:

In [23]:
vectorizer = CountVectorizer()
bow = vectorizer.fit_transform([sample_text])
dtm = pd.DataFrame(bow.toarray(), columns=vectorizer.get_feature_names_out())

# Get the vocabulary (unique words) and the bag of words matrix
#vocabulary = vectorizer.get_feature_names_out()
#bow_matrix = bow.toarray()

In [24]:
dtm

,2013,activity,allows,always,ass,assistance,australia,australian,balkan,based,...,since,standard,support,therefore,thirdparty,top,within,working,year,youth
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [25]:
dtm.shape

(1, 81)

**QUESTION:** What are the differences between the two approaches (look at the data frame content and shape results)?

#### Pilot end

Phew, that is a lot of preprocessing and quite a bit of code to get your head around. The good news is these tasks are common to almost all text analysis projects, so once you get your head around them you will be set for future work.

We could still perform some additional work to improve the substantive relevance of the text:
* Remove numbers
* Remove single-character tokens
* Remove subject-specific stop words (e.g., "charity", "charities", "australia", "year", "trust", "fund")

## Creating the full DTM

Let's create the DTM we will use for analysis. Instead of sampling one document we will preprocess all of them and make some simple adjustments to improve the text cleaning (e.g., removing numbers and common stop words). To speed up this process, let's create a function (block of code) that handles all of these steps in one go.

### Define function

In [26]:
def preprocess_text(text):

    # Tokenize the text and convert to lowercase
    words = nltk.word_tokenize(text)
    lower_words = [word.lower() for word in words]
    #print(lower_words)
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    new_stop_words = ["registered", "registration", "company", "number", "australia", 
                      "australian", "report", "charity", "charities", "charitable", "year", 
                      "end", "statement", "statements", "trustee", "trustees", "trust"]
    stop_words.update(new_stop_words)
    s_words = [word for word in lower_words if word not in stop_words]
    #print(s_words)

    # Remove punctuation and numbers
    a_words = [word for word in s_words if word.isalpha()]
    #print(a_words)

    # Remove punctuation
    english_punctuation = "-!\"#$%&()'*+,./:;<=>?@[\]^_`{|}~''“”"      # Things for removing punctuation, stopwords and empty strings
    table_punctuation = str.maketrans('','', english_punctuation) 
    p_words = [word.translate(table_punctuation) for word in a_words] 
    #print(p_words)

    # Lemmatise words
    lemmed_words = [lemmatizer.lemmatize(word) for word in p_words]
    #print(lemmed_words)

    # Stem words
    #stemmed_words = [porter.stem(word) for word in p_words]

    return ' '.join(lemmed_words)

### Clean text using function

In [27]:
# Ensure text column is valid
data["activity_desc"] = data["activity_desc"].astype(str)
data = data.dropna(subset=["activity_desc"])

In [28]:
data["clean_text"] = data["activity_desc"].apply(preprocess_text)
data[["abn", "activity_desc", "clean_text"]].sample(5)

,abn,activity_desc,clean_text
722,38159137407,MUSIKARMA provides financial support to a musi...,musikarma provides financial support music sch...
2223,94672798273,Making donations to deductible gift recipients...,making donation deductible gift recipient supp...
95,14598797167,Hanaru Women's Health Fundraising Inc has been...,hanaru woman health fundraising inc establishe...
1048,50088522098,With a return to international travel we were ...,return international travel delighted resumed ...
1558,69169548109,We provide funding to organisations operating ...,provide funding organisation operating peru pr...

### Create list of documents

We want to loop over every row in the dataset and extract the charity unique id and the cleaned activity description.

In [29]:
documents = [(row["abn"], row["clean_text"]) for _, row in data.iterrows()]
documents[0:5] # view first five elements in list of documents

[(11000761571,
  'amt support christian missionary supplementing living expense allocating mission grant project overseas keeping external conduct standard'),
 (11095489197,
  'transferring fund good overseas detail provided copyright popular daily devotional published simple english translated local language nepalese pidgin bahasa tetun printing distribution local community church school broadcast via local radio station web social medium provided assistance training resource improved best practice local board committee management responsibility good governance local initiative computer broadcast software funding capital work project constructing studio office transmission site'),
 (11115225986,
  'cultural infusion living culture program work preserve cultural diversity impoverished community africa asia recognize community cultural practice imbue member sense identity belonging'),
 (11123738223,
  'provide leadership development training support christian surfer mission enable reach serve surfing community internationally including coaching training communication platform ensuring governance structure place'),
 (11142051054,
  'preaching speaking ministering church running ministry course via zoom due covid')]

### Extract just the cleaned text for converting to DTM

In [30]:
text_data = [text for _, text in documents]
text_data[0:5]

['amt support christian missionary supplementing living expense allocating mission grant project overseas keeping external conduct standard',
 'transferring fund good overseas detail provided copyright popular daily devotional published simple english translated local language nepalese pidgin bahasa tetun printing distribution local community church school broadcast via local radio station web social medium provided assistance training resource improved best practice local board committee management responsibility good governance local initiative computer broadcast software funding capital work project constructing studio office transmission site',
 'cultural infusion living culture program work preserve cultural diversity impoverished community africa asia recognize community cultural practice imbue member sense identity belonging',
 'provide leadership development training support christian surfer mission enable reach serve surfing community internationally including coaching training communication platform ensuring governance structure place',
 'preaching speaking ministering church running ministry course via zoom due covid']

### Create a Document-Term Matrix using a Count or TF-IDF vectoriser

In [31]:
#vectorizer = CountVectorizer()#
dtm = vectorizer.fit_transform(text_data)

In [38]:
vectorizer = TfidfVectorizer()
dtm = vectorizer.fit_transform(text_data)

In [39]:
# Convert DTM into a Pandas DataFrame
dtm = pd.DataFrame(dtm.toarray(), columns=vectorizer.get_feature_names_out(), index=[doc_id for doc_id, _ in documents])

pd.set_option('display.max_rows', None) # change display options
pd.set_option('display.max_columns', None) # change display options

In [40]:
dtm

,aaa,aado,aahya,aap,aasha,aashish,aaupsl,ababa,abakan,abandoned,...,zim,zimbabwe,zimbabwean,zimpeto,zoe,zone,zonta,zoological,zoom,zumalai
11000761571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
11095489197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
11115225986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
11123738223,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
11142051054,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.307512,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821785872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99857937053,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99907435035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99983835466,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99994614897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

### Save DTM as .csv file

In [41]:
# Create a temporary downloads folder

try:
    os.mkdir("./tmp")
except:
    print("Unable to create folder: already exists")

Unable to create folder: already exists

In [42]:
dtm.to_csv("./tmp/acnc-2022-activities-dtm.csv")

## What have we learned?

Let's recap what key skills and techniques we've learned:
* **How to import modules**. You will usually need to import modules into Python to support your work. Python does come with some methods and functions that are ready to use straight away, but for text analysis tasks you'll almost certainly need to import some additional modules.
* **How to preprocess text using a standard workflow**. There are a number of preprocessing steps common to almost all text analysis projects but you still retain some control over which steps and in which order you apply them.
* **How to convert text to a number format**. The DTM / DFM is the workhorse of text analysis as it offers an efficient format for performing calculations on salient terms or features of text.
* **How to do all of the above in an efficient, clear and effective manner**.

## Conclusion

There are a number of important steps in getting text data ready for analysis. We will see why we go to the effort of creating a DTM / DFM in the next practical.

## Exercise

Create a DTM / DFM using the other file in the data folder (*acnc-overseas-activities-2021.csv*).

In [ ]:
# INSERT CODE HERE

In [ ]:
# INSERT CODE HERE

The solution is provided at the end of this notebook.

## Appendix A

### Exercise Solution

#### Creating a DTM for 2021 data on overseas charitable activities

In [ ]:
# INSERT CODE HERE

--END OF FILE--